import type { Metadata } from "next";

import "./globals.css";
import Header from "./header/page";




export const metadata: Metadata = {
  title: "js의  ",
  description: "Generated by create next app",
  icons: {
    icon: "/public/images/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container">
       <Header />
        {children}
      </body>
    </html>
  );
}
